name: Docker

jobs:

  publish-docker-hub:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get NPM Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Docker Build and Publish
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: francescorivola/connectif-2-gc-storage
          build_args: NODE_IMAGE_TAG=18.16.0-alpine,CLI_VERSION=${{ steps.package-version.outputs.current-version}}
          tag_with_sha: true
          tags: ${{ steps.package-version.outputs.current-version}},latest
